// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace GPLCC_2.Models
{
    public partial class LocalDBMSSQLLocalDBContext : DbContext
    {
        public LocalDBMSSQLLocalDBContext()
        {
        }

        public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Livre> Livre { get; set; }
        public virtual DbSet<Membre> Membre { get; set; }
        public virtual DbSet<Pret> Pret { get; set; }
        public virtual DbSet<Retard> Retard { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\billy\\Documents\\Mes_cours_2023\\programmation cote serveur\\GPLCC2\\GPLCC-2\\bdgplcc.mdf\";Integrated Security=True;Connect Timeout=30");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Livre>(entity =>
            {
                entity.HasKey(e => e.Numero)
                    .HasName("PK__Livre__7E532BC70B03EEA7");

                entity.Property(e => e.Numero).ValueGeneratedNever();

                entity.Property(e => e.Auteur)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Titre)
                    .IsRequired()
                    .HasMaxLength(50);




            });

            modelBuilder.Entity<Membre>(entity =>
            {
                entity.HasKey(e => e.Numero)
                    .HasName("PK__Membre__7E532BC728DC4BBB");

                entity.Property(e => e.Numero).ValueGeneratedNever();

                entity.Property(e => e.Nom)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Prenom)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Pret>(entity =>
            {
                entity.HasKey(e => e.Numero)
                    .HasName("PK__tmp_ms_x__7E532BC7AE41194A");

                entity.Property(e => e.Numero).ValueGeneratedNever();

                entity.Property(e => e.DateDebut).HasColumnType("date");

                entity.Property(e => e.DateFin).HasColumnType("date");

                entity.HasOne(d => d.NumLivreNavigation)
                    .WithMany(p => p.Pret)
                    .HasForeignKey(d => d.NumLivre)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pret_Livre");

                entity.HasOne(d => d.NumMembreNavigation)
                    .WithMany(p => p.Pret)
                    .HasForeignKey(d => d.NumMembre)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pret_Membre");
            });

            modelBuilder.Entity<Retard>(entity =>
            {
                entity.HasKey(e => e.NumPret)
                    .HasName("PK__tmp_ms_x__9218562525646BA9");

                entity.Property(e => e.NumPret).ValueGeneratedNever();

                entity.HasOne(d => d.NumPretNavigation)
                    .WithOne(p => p.Retard)
                    .HasForeignKey<Retard>(d => d.NumPret)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Retard_Pret");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}