// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;

namespace GPLCC_2.Models
{
    public partial class Membre
    {
        public Membre()
        {
            Pret = new HashSet<Pret>();
        }

        [Display(Name = "Numéro de membre")]
        [Required(ErrorMessage = @"Le Numéro est requis")]
        public int Numero { get; set; }

        [Required(ErrorMessage = @"Le Nom est requis")]
        public string Nom { get; set; }

        [Display(Name = "Prénom")]
        [Required(ErrorMessage = @"Le Prénom est requis")]
        public string Prenom { get; set; }

        [NotMapped]
        public string Affichage
        {
            get
            {
                return Numero + " - " + Nom + " "+Prenom;
            }
            set { Affichage = value; }
        }

        [NotMapped]
        [Display(Name = "Nom et Prénom")]
        public string Affiche
        {
            get
            {
                return Nom + " " + Prenom;
            }
            set { Affiche = value; }
        }

        public virtual ICollection<Pret> Pret { get; set; }
    }
}