// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace GPLCC_2.Models
{
    public partial class Pret
    {
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yy}")]
        [DataType(DataType.Date)]
        [Display(Name = "Début Prêt")]
        [Required(ErrorMessage = @"La date de début est requise")]
        public DateTime DateDebut { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MMM-yy}")]
        [DataType(DataType.Date)]
        [Display(Name = "Fin prêt")]
        [Required(ErrorMessage = @"La date de fin est requise")]
        public DateTime? DateFin { get; set; }

        [Required(ErrorMessage = @"Le numéro de membre est requis")]
        public int NumMembre { get; set; }

        [Required(ErrorMessage = @"Le numéro de livre est requis")]
        public int NumLivre { get; set; }

        [Display(Name = "Numéro de prêt")]
        [Required(ErrorMessage = @"Le numéro de prêt est requis")]
        public int Numero { get; set; }

        [Display(Name = "Livre Prêté")]
        public virtual Livre NumLivreNavigation { get; set; }

        [Display(Name = "Membre Emprunteur")]
        public virtual Membre NumMembreNavigation { get; set; }
        public virtual Retard Retard { get; set; }


    }
}