// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace GPLCC_2.Models
{
    public partial class Retard
    {
        [Display(Name = "Nombre Jours de retard")]
        public int NbJoursRetard { get; set; }
        public int NumPret { get; set; }

        public virtual Pret NumPretNavigation { get; set; }
    }
}